name: Sync

on:
  workflow_dispatch:
    # inputs:
    #   repo:
    #     type: string
    #     description: 'Target repo'
    #     required: false
    #     default: ''
  schedule:
    - cron: '2 13 4 * *'
  push:

concurrency:
  group: sync

# for beacon-biosignals/matrix-output
permissions:
  actions: read
  contents: read

jobs:
  prepare_matrix:
    runs-on: ubuntu-slim
    outputs:
      chunks: ${{ steps.split.outputs.matrix }}
    steps:
      - name: Split
        id: split
        run: |
          PARALLEL=10
          MATRIX=$(curl -s "https://android.googlesource.com/?format=JSON" | tail -n +2 | jq -c '.[]' | shuf | \
                    split -n l/$PARALLEL --filter='jq -Rs .' | jq -sc .)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  main:
    runs-on: ubuntu-latest
    needs: prepare_matrix
    strategy:
      fail-fast: false
      matrix:
        chunk: ${{ fromJson(needs.prepare_matrix.outputs.chunks) }}
    # outputs:
    #   failed: ${{ steps.matrix-output.outputs.json }}
    steps:
      - uses: actions/checkout@v6

      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
  
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: aosp-mirror-neo

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: df -h

      - name: List targets
        env:
          CHUNK_DATA: ${{ matrix.chunk }}
        run: echo "$CHUNK_DATA"

      - name: Sync
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          CHUNK_DATA: ${{ matrix.chunk }}
        run: |
          # set -x

          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          # not required
          git config --global init.defaultBranch main

          MAX_JOBS=15

          tmp_fifo=$(mktemp -u)
          mkfifo "$tmp_fifo"
          exec 3<>"$tmp_fifo"
          # rm "$tmp_fifo"

          for ((i=0; i<MAX_JOBS; i++)); do
            echo >&3
          done

          sudo mkdir /mnt/sync
          sudo touch /mnt/failed-repos
          sudo chown runner:runner -R /mnt/sync /mnt/failed-repos

          function log() {
            # echo "[$repo]" "${@}"
            echo "${@}"
          }

          function sync_mirror() {
            set -e

            url=$(jq -r '.clone_url' <<< "$config")
            repo=$(jq -r '.name' <<< "$config" | tr '/' '_')
            description=$(jq -r '.description // ""' <<< "$config")
            first="0"

            mkdir "$repo" && cd "$repo"

            log "Check if the mirror repository is created"
            set +e
            curl -I --fail --silent --show-error -o /dev/null "https://github.com/aosp-mirror-neo/$repo"
            ret="$?"
            set -e
            if [ "$ret" -ne 0 ]; then
              log "Creating target repo"
              gh repo create "aosp-mirror-neo/$repo" --homepage "$url" --disable-issues --disable-wiki --public --description "$description"
              first="1"
            fi

            log "Compare remotes"
            git ls-remote --quiet --heads --tags "$url" > remote-src &
            git ls-remote --quiet --heads --tags "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/aosp-mirror-neo/$repo" > remote-dist &
            wait
            set +e
            diff remote-src remote-dist > /dev/null
            ret="$?"
            set -e
            if [ "$ret" -eq 0 ]; then
              log "Mirror is synchronized. skip"
              return
            fi

            log "Cloning source repo"
            mkdir repo-dir && cd repo-dir
            git init --bare
            git remote add --mirror=fetch origin "$url"
            git remote add mirror "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/aosp-mirror-neo/$repo"

            git config unset --all remote.origin.fetch
            git config unset --all remote.mirror.fetch
            git config set --append remote.origin.fetch '+refs/heads/*:refs/heads/*'
            git config set --append remote.mirror.fetch '+refs/heads/*:refs/heads/*'
            git config set --append remote.origin.fetch '+refs/tags/*:refs/tags/*'
            git config set --append remote.mirror.fetch '+refs/tags/*:refs/tags/*'

            if [ "$first" -eq 0 ]; then
              log "Fetching from mirror"
              git fetch --quiet mirror --filter=blob:none
              log "Fetching from origin"
              git fetch --quiet origin
            else
              log "First time sync. full cloning"
              git fetch --quiet origin
            fi

            log "Pushing to mirror repo"
            set +e
            git push --quiet --mirror mirror
            ret="$?"
            set -e
            if [ "$ret" -ne 0 ]; then
              log "Failed to push, fallback"
              COMMIT_REVS=$(git rev-list --reverse HEAD)
              COUNT=0
              BATCH=60000

              for REV in $COMMIT_REVS; do
                  COUNT=$((COUNT + 1))
                  if [ $((COUNT % BATCH)) -eq 0 ]; then
                      echo "Pushing up to commit $COUNT..."
                      git push mirror $REV:refs/heads/$(git branch --show-current)
                  fi
              done

              git push mirror --mirror
            fi

            gh repo edit "aosp-mirror-neo/$repo" --default-branch "$( git remote show origin | grep "^  HEAD branch: " | cut -c 16- )"
          }

          TOTAL_COUNT=$(echo "$CHUNK_DATA" | grep -c '^')
          CURRENT=0
          cd /mnt/sync

          echo "$CHUNK_DATA" | \
          while IFS= read -r config; do
            [ -z "$config" ] && continue

            read -u 3
            CURRENT=$((CURRENT + 1))
            export config

            (
              start_time=$(date +%s.%N)
              repo=$(echo "$config" | jq -r '.name' | tr '/' '_')
              status="OK"
              echo "::group::$repo"
              log "Start"
              if ! sync_mirror "$config"; then
                log "Failed"
                echo "$repo" >> /mnt/failed-repos
                status="Failed"
              fi
              echo >&3
              log "Cleaning"
              cd "/mnt/sync/$repo"
              rm -rf repo-dir remote-src remote-dist
              end_time=$(date +%s.%N)
              log "Done ($status) ($CURRENT/$TOTAL_COUNT) ($(echo "$end_time - $start_time" | bc) sec)"
              echo "::endgroup::"
            )
            # )&
          done

          echo "Waiting for all jobs to complete"
          sleep 0.5
          for ((i=0; i<MAX_JOBS; i++)); do
            echo "waiting job: $i"
            read -u 3
          done
          echo "done"

          exec 3>&-
          exec 3<&-
          rm "$tmp_fifo"

      - name: List failed repos
        if: always()
        id: failed
        run: |
          cat /mnt/failed-repos
          echo "list=$(cat /mnt/failed-repos)" >> $GITHUB_OUTPUT
